language: shell
deploy:
- provider: s3
  access_key_id: AKIAIT4X4NDGM2WVL6VA
  secret_access_key: &1
    secure: "Z9PPeH+i6g8bPb5Qa31wwxKr7GxT/SgjVAhJu2hAARwOZZFbGi/b2LETQBUuhxC7SNGMiiI3lC+3p84eGlVLCVCg7USW9/iN+gDcWUV4AppgRr7EVEUTbpLAcKW/ewBfprhmxzWtmcZGLLmhTuS9vqtGEjhpWtucJw7fLGgUxEFHJux6K1xzOXWeHOaI4efsY/sCtOb/pvEV2A3ZwcvLczbaHqmjMnVNvUusyFtwRWhNNglwr7lAXQr/YfL7XwU0yCPCACxXFwv527L6oUp20SuYQdiCoh/ysDxh5Yu7VW5Yv/t3gwa+7j9f/7ivj2qTkCeAxTTfOuSsOYw+ZOai+P+e7JjACcuTS7K3VFmxJSExfV3Yc5VZNnfuS6IYZguoFcuM9BwgwXVaTTGwqrELhpsl+GR60qmMSiXQ7VDkvA+W9XMmB7NIqyGr0zW6OsxutzRpRNCcD3sNdg9/aFb9rpwED/L9CYwnDfG3VRw+8+RTJ2e7qU0s4soNGthUPjDQ7fHRQ77JVgarepNFmDu7JHQyrGKIuGq0WmndtucHHJiXVk9Y2vv8eaBsp+/Ee4WKPYxQ0+ukYQaecS5PnQzPQSIhsSknB0uenilTTED0OOLVntQ6M4nyRMMcF2JL4BekSri6aXbsEII27y13F0z7oZMV7KXGZ6uvUJddgYeIeUs="
  bucket: buttons.octoblu.com
  endpoint: buttons.octoblu.com.s3-website-us-west-2.amazonaws.com
  region: us-west-2
  on:
    branch: master
